LABELS = {
    "do": {
        "title": "Comprobante de pago",
        "gross_salary": "Salario bruto",
        "gross_payment": "Pago bruto",
        "net_payment": "Pago neto",
        "discounts": "Descuentos",
        "sfs": "SFS",
        "afp": "AFP",
        "isr": "ISR",
        "other": "Otros",
        "total": "Total",
    },
    "usa": {
        "title": "Paystub Payment",
        "gross_salary": "Gross Salary",
        "gross_payment": "Gross Payment",
        "net_payment": "Net Payment",
        "discounts": "Deductions",
        "sfs": "Health Insurance",
        "afp": "Social Security",
        "isr": "Taxes",
        "other": "Others",
        "total": "Total",
    },
}
